apiVersion: 1
datasources:
  - name: PostgreSQL Academico
    type: postgres
    access: proxy
    url: postgres:5432
    database: payments
    user: app
    secureJsonData:
      password: app_password
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 300
    isDefault: false
